server:
  port: 8000

spring:
  application:
    name: 天亮后台
  servlet:
    multipart:
      max-file-size: 10MB # 限制文件上传的大小
      max-request-size: 10MB
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.223.94:3306/training
    hikari:
      max-lifetime: 60000
  redis:
    host: 121.196.223.94
    port: 6379
    database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000ms
        # 连接池中的最大空闲连接数
        max-idle: 20
        # 连接池中的最小空闲连接数
        min-idle: 5
    timeout: 5000ms
logging:
  level:
    com.example.demo: debug
    sql: debug
    web: debug

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

fdfs:
  connect-timeout: 1000
  so-timeout: 1000
  thumb-image:
    height: 60
    width: 60
  tracker-list:
    - tx.gqz2019.top:22122
  pool:
    max-total: 10
fastdfs:
  domain: http://tx.gqz2019.top:8888